"""metrics_service.py — Safe, SELECT-only DuckDB executor over Evidence parquet files.

The agent (Gemini) generates the SQL. This service:
 1. Validates the SQL is a read-only SELECT statement (no DDL/DML).
 2. Opens an ephemeral in-memory DuckDB connection.
 3. Registers parquet files as virtual views using read_parquet().
 4. Executes the query and returns rows + a plain-English summary.

Parquet files are generated by Evidence after running:
    npx evidence sources   (inside the frontend/ directory)

Parquet location:
    {EVIDENCE_META_DIR}/{source}/{table}/tmp/*.parquet
    e.g.  frontend/.evidence/meta/needful_things/orders/tmp/orders.parquet
"""

from __future__ import annotations

import logging
import re
from pathlib import Path
from typing import Any

import duckdb

from app.core.config import settings

logger = logging.getLogger(__name__)

# ── Safety ────────────────────────────────────────────────────────────────────

# Patterns that must not appear in agent-generated SQL
_FORBIDDEN_PATTERNS = re.compile(
    r"\b(INSERT|UPDATE|DELETE|DROP|CREATE|ALTER|TRUNCATE|COPY|ATTACH|PRAGMA|LOAD)\b",
    re.IGNORECASE,
)


def _assert_safe_sql(sql: str) -> None:
    """Raise ValueError if the SQL contains dangerous statements."""
    stripped = sql.strip()
    if not stripped.upper().startswith("SELECT"):
        raise ValueError(f"Only SELECT statements are allowed. Got: {stripped[:60]!r}")
    m = _FORBIDDEN_PATTERNS.search(stripped)
    if m:
        raise ValueError(f"Forbidden SQL keyword '{m.group()}' detected.")


# ── Parquet view registration ─────────────────────────────────────────────────

def _build_parquet_views(conn: duckdb.DuckDBPyConnection) -> None:
    """
    Register every Evidence parquet dataset as DuckDB views under three aliases:

        needful_things.orders   ← schema-qualified (as in Evidence SQL pages)
        needful_things__orders  ← snake_case identifier
        orders                  ← plain table name

    Evidence writes parquet files at:
        {evidence_meta_dir}/{source}/{table}/{table}.parquet
    """
    meta_dir = Path(settings.evidence_meta_dir)
    if not meta_dir.exists():
        logger.warning("Evidence data dir not found: %s — no views registered", meta_dir)
        return

    registered: list[str] = []
    for parquet_file in meta_dir.glob("*/*/*.parquet"):
        source = parquet_file.parent.parent.name   # e.g. "needful_things"
        table  = parquet_file.parent.name           # e.g. "orders"
        path   = str(parquet_file).replace("\\", "/")

        # 1. Create the DuckDB schema (= Evidence source name)
        #    so that "needful_things.orders" resolves as schema.table
        conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{source}"')

        # 2. Schema-qualified view: needful_things.orders
        conn.execute(
            f'CREATE OR REPLACE VIEW "{source}"."{table}" '
            f"AS SELECT * FROM read_parquet('{path}')"
        )

        # 3. Snake-case alias: needful_things__orders
        conn.execute(
            f'CREATE OR REPLACE VIEW "{source}__{table}" '
            f"AS SELECT * FROM read_parquet('{path}')"
        )

        # 4. Plain alias: orders
        conn.execute(
            f'CREATE OR REPLACE VIEW "{table}" '
            f"AS SELECT * FROM read_parquet('{path}')"
        )

        registered.append(f"{source}.{table}")
        logger.debug("Registered view: %s.%s → %s", source, table, path)

    logger.info("Parquet views registered: %s", registered)



# ── Public API ────────────────────────────────────────────────────────────────

def run_query(sql: str) -> dict[str, Any]:
    """
    Execute a SELECT query over Evidence parquet data.

    Returns:
        {
            "sql":     str,          # the query that was executed
            "columns": list[str],    # column names
            "rows":    list[dict],   # result rows as dicts
            "summary": str,          # short plain-English description
        }

    Raises:
        ValueError  if the SQL is unsafe (DDL/DML detected)
        RuntimeError on DuckDB execution errors
    """
    _assert_safe_sql(sql)

    conn = duckdb.connect()  # ephemeral, in-memory
    try:
        _build_parquet_views(conn)
        rel = conn.execute(sql)
        columns = [desc[0] for desc in rel.description]
        raw_rows = rel.fetchall()
        rows = [dict(zip(columns, row)) for row in raw_rows]

        # Build a terse summary
        summary = _build_summary(rows, columns)

        logger.info("Query executed: %d row(s) returned", len(rows))
        return {
            "sql": sql,
            "columns": columns,
            "rows": rows,
            "summary": summary,
        }
    except duckdb.Error as e:
        raise RuntimeError(f"DuckDB query failed: {e}") from e
    finally:
        conn.close()


def _build_summary(rows: list[dict], columns: list[str]) -> str:
    """Generate a plain-English result summary suitable for the chat UI."""
    if not rows:
        return "No data found for this query."

    if len(rows) == 1 and len(columns) == 1:
        val = list(rows[0].values())[0]
        col = columns[0]
        # Format large numbers nicely
        if isinstance(val, (int, float)):
            formatted = f"${val:,.2f}" if "sale" in col.lower() or "revenue" in col.lower() else f"{val:,.2f}"
            return f"{col.replace('_', ' ').title()}: {formatted}"
        return f"{col.replace('_', ' ').title()}: {val}"

    if len(rows) <= 5:
        # Small result set — emit as a readable list
        lines = []
        for row in rows:
            parts = [f"{k.replace('_', ' ')}: {_fmt_val(v)}" for k, v in row.items()]
            lines.append("  • " + " | ".join(parts))
        return "\n".join(lines)

    # Larger result set — just report count
    return f"{len(rows)} rows returned across columns: {', '.join(columns)}"


def _fmt_val(v: Any) -> str:
    if isinstance(v, float):
        return f"{v:,.2f}"
    if isinstance(v, int):
        return f"{v:,}"
    return str(v)
