"""page_context_service.py — Load Evidence page summary JSON for the agent.

The page summary is generated by running:
    python parse_pages.py   (inside the frontend/ directory)

It is then served as a static file at:
    frontend/static/page_json_descriptions/{page}.json

And exposed as an API at:
    GET /page-summary/{page}
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from app.core.config import settings

logger = logging.getLogger(__name__)


def get_page_context(page: str) -> dict | None:
    """
    Load the JSON page summary for *page* (e.g. 'index', 'settings').

    Returns the parsed dict or None if the file doesn't exist.
    """
    page_name = page.strip("/").replace("/", "_") or "index"
    json_path = Path(settings.page_descriptions_dir) / f"{page_name}.json"

    if not json_path.exists():
        logger.warning("Page description not found: %s", json_path)
        return None

    try:
        data = json.loads(json_path.read_text(encoding="utf-8"))
        logger.info("Loaded page context for '%s' (%d queries, %d filters)",
                    page_name, len(data.get("queries", [])), len(data.get("filters", [])))
        return data
    except Exception as e:
        logger.error("Failed to parse page description %s: %s", json_path, e)
        return None


def format_context_for_llm(context: dict) -> str:
    """
    Render the page context dict into a compact text block suitable for
    injection into the LLM system or user message.
    """
    if not context:
        return ""

    lines: list[str] = [
        f"## Dashboard Page: {context.get('title', context.get('page', 'unknown'))}",
    ]

    if context.get("description"):
        lines.append(f"Description: {context['description']}")

    # Filters
    if context.get("filters"):
        lines.append("\n### Available Filters (Dropdown inputs)")
        for f in context["filters"]:
            name = f.get("input_name", "?")
            label = f.get("label") or name
            multi = " (multi-select)" if f.get("multiple") else ""
            lines.append(f"  - `{name}` — {label}{multi}")

    # SQL Queries defined on this page
    if context.get("queries"):
        lines.append("\n### SQL Queries Available on This Page")
        for q in context["queries"]:
            lines.append(f"  **{q['name']}**")
            lines.append(f"    Columns: {', '.join(q.get('columns', []))}")
            lines.append(f"    References: {', '.join(q.get('references', []))}")
            if q.get("filter_inputs"):
                lines.append(f"    Filter inputs used: {', '.join(q['filter_inputs'])}")
            lines.append(f"    SQL:\n```sql\n{q['sql']}\n```")

    # Charts
    if context.get("charts"):
        lines.append("\n### Charts on This Page")
        for c in context["charts"]:
            lines.append(f"  - {c['type']}: \"{c.get('title')}\" — data={c.get('data_query')}, x={c.get('x')}, y={c.get('y')}")

    return "\n".join(lines)
